// Flat ESLint config — relies on @nuxt/eslint which wires up Vue + TypeScript.
// The `.nuxt/eslint.config.mjs` file is generated by `nuxt prepare` (runs as
// the `postinstall` script in package.json), so make sure to install deps
// before running ESLint locally.
import withNuxt from "./.nuxt/eslint.config.mjs";

export default withNuxt(
  // Project-level overrides
  {
    rules: {
      "vue/multi-word-component-names": "off",
      "vue/html-self-closing": [
        "warn",
        {
          html: { void: "always", normal: "always", component: "always" },
        },
      ],
    },
  },
);
