"""UserLibrary — books a user owns after a successful purchase.

One row per (user, book). ``watermarked_url`` points at the per-buyer
PDF generated by the post-purchase Celery task; ``order_id`` lets us
trace each acquisition back to its invoice. Free books also land here
via the same flow (commission_rate = 0, no Payme call) so the
"owned vs. catalog" check is a single table lookup.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import DateTime, ForeignKey, Integer, String, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, UUIDMixin

if TYPE_CHECKING:
    from app.models.book import Book
    from app.models.order import Order
    from app.models.user import User


class UserLibrary(UUIDMixin, Base):
    __tablename__ = "user_libraries"
    __table_args__ = (
        UniqueConstraint("user_id", "book_id", name="uq_user_libraries_user_book"),
    )

    user_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    book_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("books.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    order_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("orders.id"),
        nullable=True,
    )

    watermarked_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    downloaded_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0"
    )
    last_downloaded_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    acquired_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default="now()"
    )

    # Relationships
    user: Mapped[User] = relationship()
    book: Mapped[Book] = relationship()
    order: Mapped[Order | None] = relationship()
