/**
 * Central icon registry, separated from the Icon.vue SFC so non-component
 * code (pickers, autocompletes, types) can import the icon list without
 * triggering the Vue SFC compiler. `<script setup>` doesn't allow named
 * exports, so this file is the canonical home for the mapping.
 *
 * Uses @heroicons/vue (24px outline + solid sets). Tree-shaking keeps the
 * bundle lean because each icon is imported by name — only icons listed
 * here ship to the client.
 */
import {
  AcademicCapIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowTopRightOnSquareIcon,
  ArrowUpTrayIcon,
  Bars3Icon,
  BanknotesIcon,
  BookOpenIcon,
  BuildingLibraryIcon,
  BuildingOfficeIcon,
  CheckCircleIcon,
  CheckIcon,
  ChartBarIcon,
  ChatBubbleLeftEllipsisIcon,
  ChevronDownIcon,
  ClipboardDocumentCheckIcon,
  ClipboardDocumentListIcon,
  Cog6ToothIcon,
  ComputerDesktopIcon,
  CurrencyDollarIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FolderOpenIcon,
  GiftIcon,
  HandRaisedIcon,
  HeartIcon,
  HomeIcon,
  InboxIcon,
  InboxStackIcon,
  KeyIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MoonIcon,
  NewspaperIcon,
  PencilSquareIcon,
  PlusIcon,
  ScaleIcon,
  ShoppingCartIcon,
  SparklesIcon,
  SunIcon,
  StarIcon,
  TrashIcon,
  UserCircleIcon,
  UserPlusIcon,
  UsersIcon,
  WrenchScrewdriverIcon,
  XMarkIcon,
} from "@heroicons/vue/24/outline";
import {
  CheckCircleIcon as CheckCircleSolidIcon,
  ExclamationTriangleIcon as ExclamationTriangleSolidIcon,
  HeartIcon as HeartSolidIcon,
  StarIcon as StarSolidIcon,
} from "@heroicons/vue/24/solid";

export const ICONS = {
  // --- generic ---
  "home": HomeIcon,
  "settings": Cog6ToothIcon,
  "search": MagnifyingGlassIcon,
  "menu": Bars3Icon,
  "close": XMarkIcon,
  "plus": PlusIcon,
  "check": CheckIcon,
  "check-circle": CheckCircleIcon,
  "check-circle-solid": CheckCircleSolidIcon,
  "warning": ExclamationTriangleIcon,
  "warning-solid": ExclamationTriangleSolidIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-path": ArrowPathIcon,
  "external": ArrowTopRightOnSquareIcon,
  "external-link": ArrowTopRightOnSquareIcon,
  "upload": ArrowUpTrayIcon,
  "chevron-down": ChevronDownIcon,
  "trash": TrashIcon,
  "pencil": PencilSquareIcon,
  "document": DocumentTextIcon,
  "key": KeyIcon,
  "lock": LockClosedIcon,
  "eye": EyeIcon,
  "eye-slash": EyeSlashIcon,
  "envelope": EnvelopeIcon,
  "envelope-open": EnvelopeOpenIcon,
  "sparkles": SparklesIcon,
  "moon": MoonIcon,
  "sun": SunIcon,
  "desktop": ComputerDesktopIcon,
  "user-circle": UserCircleIcon,
  "user-plus": UserPlusIcon,
  "users": UsersIcon,
  "hand": HandRaisedIcon,

  // --- commerce / content ---
  "book": BookOpenIcon,
  "library": BuildingLibraryIcon,
  "institution": BuildingOfficeIcon,
  "inbox": InboxIcon,
  "inbox-stack": InboxStackIcon,
  "cart": ShoppingCartIcon,
  "heart": HeartIcon,
  "heart-solid": HeartSolidIcon,
  "gift": GiftIcon,
  "star": StarIcon,
  "star-solid": StarSolidIcon,
  "chat": ChatBubbleLeftEllipsisIcon,
  "news": NewspaperIcon,
  "folder": FolderOpenIcon,
  "chart": ChartBarIcon,
  "clipboard-list": ClipboardDocumentListIcon,
  "clipboard-check": ClipboardDocumentCheckIcon,
  "money": BanknotesIcon,
  "currency": CurrencyDollarIcon,
  "scale": ScaleIcon,
  "wrench": WrenchScrewdriverIcon,
  "academic": AcademicCapIcon,
} as const;

export type IconName = keyof typeof ICONS;

/** Sorted list of every icon name, exported for pickers / autocompletes. */
export const ICON_NAMES = Object.keys(ICONS) as IconName[];
