#!/usr/bin/env bash
# First-time production setup in IP:port mode (no domain yet).
#
# What it does:
#   1. Generates .env from .env.prod.example with random secrets +
#      IP-based URLs (skipped if .env already exists).
#   2. Writes docker-compose.override.ip.yml — binds backend/frontend/
#      minio to 0.0.0.0 and parks nginx+certbot behind a "disabled"
#      profile so they don't start without a domain.
#   3. Builds images.
#   4. Brings services up.
#   5. Runs alembic + seed_categories.
#   6. Prints how to create the first admin + next steps.
#
# Usage:
#   scripts/bootstrap-prod.sh             # auto-detect server IP
#   scripts/bootstrap-prod.sh 1.2.3.4     # explicit IP

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [[ ! -f docker-compose.prod.yml ]]; then
    echo "Not at project root — expected docker-compose.prod.yml here" >&2
    exit 1
fi

# --- detect server IP -------------------------------------------------------
SERVER_IP="${1:-}"
if [[ -z "$SERVER_IP" ]]; then
    SERVER_IP=$(curl -s --max-time 3 ifconfig.me 2>/dev/null \
        || curl -s --max-time 3 ipinfo.io/ip 2>/dev/null \
        || true)
fi
if [[ -z "$SERVER_IP" ]]; then
    echo "Server IP'ni avto-aniqlay olmadim. Aniq IP'ni argument qilib ber:" >&2
    echo "  $0 1.2.3.4" >&2
    exit 1
fi
echo "==> server IP: $SERVER_IP"

# --- generate .env ----------------------------------------------------------
if [[ -f .env ]]; then
    echo "==> .env mavjud, qayta yaratmayman (parol/URL'larni qo'lda tahrirlash mumkin)"
else
    echo "==> .env'ni .env.prod.example dan yaratyapman"
    cp .env.prod.example .env

    POSTGRES_PW=$(openssl rand -hex 24)
    MINIO_PW=$(openssl rand -hex 24)
    JWT_KEY=$(openssl rand -hex 32)
    MEILI_KEY=$(openssl rand -hex 32)

    sed -i "s|change-me-strong-postgres-password|$POSTGRES_PW|g" .env
    sed -i "s|change-me-strong-minio-password|$MINIO_PW|g" .env
    sed -i "s|change-me-generate-with-openssl-rand-hex-32|$JWT_KEY|g" .env
    sed -i "s|change-me-32-chars-minimum-meili-master-key|$MEILI_KEY|g" .env

    # IP-based URLs (domenga o'tilganida switch-to-domain.sh almashtiradi)
    sed -i "s|^NUXT_PUBLIC_API_BASE=.*|NUXT_PUBLIC_API_BASE=http://$SERVER_IP:8307/api/v1|" .env
    sed -i "s|^NUXT_PUBLIC_SITE_URL=.*|NUXT_PUBLIC_SITE_URL=http://$SERVER_IP:8308|" .env
    sed -i "s|^FRONTEND_URL=.*|FRONTEND_URL=http://$SERVER_IP:8308|" .env
    sed -i "s|^CORS_ORIGINS=.*|CORS_ORIGINS=http://$SERVER_IP:8308,http://$SERVER_IP:8307|" .env
    sed -i "s|^MINIO_PUBLIC_ENDPOINT=.*|MINIO_PUBLIC_ENDPOINT=http://$SERVER_IP:8302|" .env

    echo "==> SMTP_HOST/USER/PASSWORD va EMAIL_FROM qiymatlarini .env da qo'lda to'ldir"
    echo "    (parol qayta tiklash + ro'yxatdan o'tish maktublari uchun kerak)"
fi

# --- ensure BIND=0.0.0.0 so ports are reachable from outside ----------------
# These get reset to 127.0.0.1 (default) by switch-to-domain.sh.
echo "==> port bind manzillarini 0.0.0.0'ga sozlayapman"
for var in POSTGRES_BIND REDIS_BIND MINIO_API_BIND MINIO_CONSOLE_BIND \
           MEILISEARCH_BIND BACKEND_BIND FRONTEND_BIND; do
    if grep -q "^$var=" .env; then
        sed -i "s|^$var=.*|$var=0.0.0.0|" .env
    else
        echo "$var=0.0.0.0" >> .env
    fi
done

# --- override file: skip nginx + certbot (no domain yet) --------------------
echo "==> docker-compose.override.ip.yml yarataman (nginx+certbot o'chiq)"
cat > docker-compose.override.ip.yml <<'EOF'
# Auto-generated by scripts/bootstrap-prod.sh — IP:port mode.
#
# nginx + certbot is parked behind a "domain-only" profile so they
# don't start without a domain. Service ports themselves are bound to
# 0.0.0.0 via the *_BIND env vars in .env (which switch-to-domain.sh
# resets to 127.0.0.1).
#
# Domenga o'tilganda scripts/switch-to-domain.sh bu faylni o'chiradi.

services:
  nginx:
    profiles: ["domain-only"]
  certbot:
    profiles: ["domain-only"]
EOF

COMPOSE="docker compose -f docker-compose.prod.yml -f docker-compose.override.ip.yml"

# --- build + up -------------------------------------------------------------
echo "==> image'larni yig'yapman (5-10 daqiqa)"
$COMPOSE build

echo "==> servislarni ko'tarayapman"
$COMPOSE up -d

echo "==> backend healthy bo'lishini kutyapman"
for i in $(seq 1 60); do
    if curl -sf "http://localhost:8307/health" >/dev/null 2>&1; then
        echo "    backend healthy"
        break
    fi
    sleep 2
    if [[ $i -eq 60 ]]; then
        echo "    backend 2 daqiqada javob bermadi, davom etyapman (log'ni tekshir)" >&2
    fi
done

# --- migrate + seed ---------------------------------------------------------
echo "==> alembic upgrade head"
$COMPOSE exec -T backend alembic upgrade head

echo "==> kategoriyalar seed"
$COMPOSE exec -T backend python -m app.scripts.seed_categories

# --- done -------------------------------------------------------------------
cat <<EOF

================================================================
  Tayyor! Sayt quyidagi manzillarda ishlayapti:

    Frontend       : http://$SERVER_IP:8308
    Backend (docs) : http://$SERVER_IP:8307/docs
    MinIO console  : http://$SERVER_IP:8303
    Meilisearch    : http://$SERVER_IP:8304

  Birinchi adminni yarat:

    $COMPOSE exec backend \\
        python -m app.scripts.create_admin \\
        --email you@example.com \\
        --password 'StrongPass!2026' \\
        --name 'Admin'

  Loglar:
    $COMPOSE logs -f backend
    $COMPOSE logs -f frontend

  IP mode'da kelajakda komandalar shu prefiks bilan bo'ladi:
    $COMPOSE <command>

  Domenga o'tish vaqti kelganda:
    scripts/switch-to-domain.sh monografiya.com
================================================================
EOF
